baseURL = "http://plus360.eu/"
languageCode = "en-us"
title = "plus360"
theme = "p360"

[params]
  titleWord = "plus"
  titleDigit = "360"
  email = "info@plus360.eu"
  phone = "+49 (30) 000 000 000"
  phoneLink = ""
