baseURL = "https://plus360.eu/"
languageCode = "de"
title = "plus360 — Google Street View, Virtuelle Rundgänge, Innen- und Architekturfotografie"
theme = "p360"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Wir bieten als 360° Panorama Fotografie  für Ihrem Firmen- und Geschäfts"
  titleWord = "plus"
  titleDigit = "360"
  email = "info@plus360.eu"
  phone = "+49 (30) 000 000 000"
  phoneLink = ""
